import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/navBar/sidebar"
import Header from "@/components/header/header"

const poppinsFont = Poppins({
  weight: ["100", "200" , "300" , "400" , "500" , "600" , "700" , "800" ,"900" ],
  variable: "--font-poppins",
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppinsFont.variable} antialiased relative`}
      >
        
   <Sidebar />
    <Header />
        {children}
      </body>
    </html>
  );
}
